# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150902175238 on 2015-09-05 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_added_url', models.URLField()),
                ('obfuscated_url', models.URLField()),
            ],
        ),
    ]
