# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150902175238 on 2015-09-07 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloak', '0002_url_obfuscated_url_click_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='obfuscated_url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
